server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现
          lower-case-service-id: true  # 服务名小写
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8082"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: static-resources
          uri: file:///static/
          predicates:
            - Path=/
            - Path=/index.html
            - Path=/static/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
          filters:
            - RewritePath=/api/media/(?<segment>.*), /random/$\{segment}

        - id: security-service
          uri: lb://security
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.31.106:8848
        user-name: nacos
        password: nacos
        naming-load-cache-at-start: true
        register-enabled: true
        namespace: 0
        group: DEFAULT_GROUP
      config:
        import-check:
          enabled: false  # 禁用配置导入检查

# 暴露所有Actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
    org.springframework.cloud.gateway.filter: debug
    org.springframework.cloud.gateway.filter.factory: debug
    org.springframework.cloud.gateway.route: debug
    org.springframework.web: debug
    org.springframework.http: debug
