server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现
          lower-case-service-id: true  # 服务名小写
      routes:
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#          - Path=/api/user/**
#        filters:
#          - StripPrefix=1
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.31.106:8848
        user-name: nacos
        password: nacos
        naming-load-cache-at-start: true
        register-enabled: true
        namespace: 0
        group: DEFAULT_GROUP
      config:
        import-check:
          enabled: false  # 禁用配置导入检查

# 暴露所有Actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
