server:
  port: 8089

spring:
  application:
    name: security
  security:
    user:
        name: admin
        password: admin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现
          lower-case-service-id: true  # 服务名小写
      routes:
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#          - Path=/api/user/**
#        filters:
#          - StripPrefix=1
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.31.106:8848
        user-name: nacos
        password: nacos
        naming-load-cache-at-start: true
        register-enabled: true
        namespace: 0
        group: DEFAULT_GROUP
      config:
        import-check:
          enabled: false  # 禁用配置导入检查
  datasource:
    url: jdbc:mysql://192.168.31.106:3306/wakaba_mutsumi?useSSL=false
    username: wakaba_mutsumi
    password: wakaba_mutsumi
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 新增Redis配置
  redis:
    host: 192.168.31.106
    port: 26739
    password: EMFFkhXxtKDwHpmp
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# 暴露所有Actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
mybatis:
  mapper-locations: classpath:cn/helloworld1999/common/mapper/*.xml
  type-aliases-package: cn.helloworld1999.common.domain
