server:
  port: 8089

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: security
  security:
    user:
        name: admin
        password: admin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现
          lower-case-service-id: true  # 服务名小写
      routes:
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#          - Path=/api/user/**
#        filters:
#          - StripPrefix=1
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.31.106:8848
        user-name: nacos
        password: nacos
        naming-load-cache-at-start: true
        register-enabled: true
        namespace: 0
        group: DEFAULT_GROUP
      config:
        import-check:
          enabled: false  # 禁用配置导入检查
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: cn.helloworld1999.common.domain
    configuration:
      map-underscore-to-camel-case: true
  datasource:
    url: jdbc:mysql://192.168.31.106:3306/wakaba_mutsumi?useSSL=false
    username: wakaba_mutsumi
    password: wakaba_mutsumi
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 新增Redis配置
  redis:
    host: 192.168.31.106
    port: 26739
    password: EMFFkhXxtKDwHpmp
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# 暴露所有Actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
mybatis:
  mapper-locations: classpath:cn/helloworld1999/common/mapper/*.xml
  type-aliases-package: cn.helloworld1999.common.domain
security:
  token:
    secret: QMQfdNyXMJUbQX7CCppBfPA2t3CwmbpvtNjzWef3unuVtjarA75xd5yVBxDPSkC7SaHbunrCXEeZVQJ8bj2umGpajUBybMKNH848B6UusVc4m2vyBmRTUwfG36AJC6H6duVt4wGKFJMFZ2ysBYxp2z6nN2QuPhQxPPfw2hcQdfXdfQvdSEjpADp6Yvr8TVSF4wWsjYnjJkRUW6F5v84B5Q2WKJvQDcnPEJYY4ex7ZSaKfacY42CVBsmuDpXsaRTsp4h2xbYBMhJukp4jen5UUmmFnjEfkfJPMMnxadkWvkuH5R5Gs7G2kW6WMk8T43CbXQeF2v8YFKAxZPHkW2PjfTxMXtjSwvPBn44aATTSynQKK2ddARjZuPJHd32Szu5GDjReHut8HVvajbsUb3E7BzUZwtXkvjJjdkDY8mx5rMbudxsUStkz7yj6BxvFMyPNPWppS2FzVyntDHTeYR4CSmtfaJWWaBYrt4dFb6vSfbHJy6PCKBHWHCXzC5TnC4He
    strategy: jwt